src/commands/test/util/browser-tests-runner/index.js
src/commands/test/util/browser-tests-runner/lasso-istanbul-plugin.js

This makes phantomJS and istanbul-lib-instrument configurable from `.marko-devtools.js`. 
```js
module.exports = function(markoDevtools) {
markoDevtools.configure({
istanbulLibInstrumentOptions: {
esModules: true
},
phantomOptions: {
useColors: true,
ignoreResourceErrors: true,
viewportSize: {
width: 1280,
height: 1024
}
}
});
};
```
Also, it seems only with browser tests, mochaphantomjs was not exiting properly (either on success or failure. `then` and `catch` are being executed properly and the server closed, but the process just hangs. This is one area I wouldn't mind discuss more as I'm not sure if this is expected or not with mochaphantomjs. (I'd expect it to work out of the box) 
However, manually exiting the process makes the tests work as expected. I'll make some comments inline.

Add phantomJS options and fix exit

---

README.md
package.json
src/commands/test/util/browser-tests-runner/index.js

Since having copies of a `browser.json` in every component directory is rather annoying I figured it would be nice to have the option to specify any shared dependencies on the `config` object within the project's `marko-devtools.js`.

Allow shared dependencies to be specified from marko-devtools.js

---

package.json
src/commands/test/util/browser-tests-runner/index.js

This PR introduces `porti`, which is used for finding unused ports. Before, `marko-devtools` always ran tests on port `8080`, which is also the default port for `marko-starter-demo`. You could not be running a demo app and run tests at the same time.
Additionally, some minor jshint fixes.

Introduce porti for finding an unused port for running tests.

---

README.md
src/commands/test/util/browser-tests-runner/BrowserContext.js

Was moving some of my v3 components over to v4 and found that there were an issue creating the components when running tests. Here is a small fix that allows v4 components to be tested when retrieving the `widget` attribute from the browser context. I also added a `component` getter as an alternative alias. I figured that since pretty much all references of "widgets" was replaced with "components" in v4, the `component` attribute would make a more sense for someone who hasn't used an older version of marko.
P.S. Congrats on the release. I'm loving v4 so far and switching from v3 to v4 was a breeze.

Use getComponent when dealing with marko v4 renderResult

---

src/commands/test/util/loadTests.js

This allows users to be able to pass custom testMatchers so one can fine tune which tests are run in each environment. 
This is important because when we have different bundles for mobile/desktop and maybe in the future native? (who knows) we want to be able to only run some tests for some bundles. Currently the behavior has been to run all the tests that follow certain pattern under the `**/test/*.js` blob. We are changing that now.
In this example I'm changing the matcher regular expression for the desktop i.e. large-screen to only accept things like `[utils-]test[.browser|.server].js` and it will not run things like `test.browser.mobile.js` 
but if we run tests with the env variable TEST_PLATFORM set to 'mobile' then our testMatcher will accept *only* tests of the shape …

Adds pluggable testMatcher function in the configuration files

---

package.json
src/commands/create/run.js

This changes `marko create` to download directly from GitHub. 
**Sources**
By default `marko-starter-demo` is used, but you can also specify another repo:
```bash
marko create color-picker:my-new-app # marko-js-samples/marko-color-picker
```
```bash
marko create demo-advanced:my-new-app # marko-js-samples/marko-starter-demo-advanced
```
```bash
marko create ui-components-library:my-new-app # marko-js-samples/ui-component-library
```
```bash
marko create mlrawlings/marko-demo:my-new-app # mlrawlings/marko-demo
```
**Other stuff**
- `marko create` also now runs `npm install` for you.
- progress indicator powered by [ora](https://github.com/sindresorhus/ora)

create from repo

---

src/commands/test/util/browser-tests-runner/BrowserContext.js

It would be useful to get the underlying dom nodes for a component if a user has functions they wish to test that receive dom elements as input
```js
test('stuff', (ctx) => {
let container = ctx.render({}).container;
let parsedInput = parseInputValue(container.querySelector('input'));
expect(parsedInput).to.equal('foo');
})
```

add container getter to browser context

---

README.md
package.json
src/commands/test/util/browser-tests-runner/index.js
src/commands/test/util/browser-tests-runner/mocha-run.js
src/commands/test/util/browser-tests-runner/setup.js

Several months ago the maintainer of PhantomJS is [announced he'd be stepping down from the project](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE). 
Last week the chrome team unveiled [puppeteer](https://github.com/GoogleChrome/puppeteer): a headless chrome api for node.  One big benefit of puppeteer is that it ships with its [own version of chromium that is guaranteed to work with the API](https://github.com/GoogleChrome/puppeteer#default-runtime-settings).
<s>It does, however, require node 7.x+ as it uses `async`/`await`</s>
`puppeteer@0.10` supports node 6!
**TODO:**

use puppeteer instead of phantomjs

---

package.json

`require-self-ref` is used in the tests, but not listed in `package.json`. I added it as a `devDependency`.
https://github.com/marko-js/marko-cli/blob/245b9bbacbf2c8920faae0e757137eb357102a9f/src/util/hasMarkoCliInstalled.test.js#L1

add missing require-self-ref dependency

---

src/cli.js

Using the command without arguments
```sh
$ marko
```
Before:
```
Invalid command: undefined
Allowed commands: test create compile
```
Now
```
Usage: marko <command> arg0 arg1 ... argn
Allowed commands: test create compile
```

Show usage in case no command is passed

---

README.md
package.json
src/commands/test/run.js

Follow up PR to https://github.com/marko-js/marko-util/pull/8
Allows passing `puppeteerOptions` to `@marko/test` when launching Puppeteer.

add puppeteer options

---

packages/prebuild/package-lock.json
packages/test/src/util/browser-tests-runner/browser-dependencies/browser-context.js

Copy of PR https://github.com/marko-js/marko-cli/pull/83 but with package-lock.json updated.
Marko v4 does not support RenderResult.html, but both v4 and v3 support RenderResult.toString().
This fixes browser rendering in tests for Marko v4.

Removing RenderResult.html in favor of RenderResult.toString()

---

README.md
package-lock.json
package.json
packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/commands/test/parse.js
packages/compile/package.json
packages/prebuild/package-lock.json
packages/test/package.json
packages/test/src/index.js
packages/test/src/util/browser-tests-runner/browser-dependencies/index.js
packages/test/src/util/browser-tests-runner/driver.js
packages/test/src/util/browser-tests-runner/server.js
packages/test/src/util/browser-tests-runner/util/wdio-defaults.js
packages/test/src/util/server-tests-runner/index.js

* Improve test resilience and timeout handling (especially with browserstack).
* Prevents timeouts by manually polling webdriver command until completion.
* Added delay overrides for launchers (browser stack needed a 10s delay).
* Warmup lasso cache before calling webdriver to decrease the total time the driver is waiting.
* Automatically re-run tests when refreshing in `no-exit` mode.
* Format stack traces to point to the proper locations in nodejs.
* Node args are now forwarded, allowing things like '--inspect' to pass through.
* Added new suiteTimeout option.

Misc fixes / improvements to the test command.

---

README.md
packages/cli/src/commands/test/parse.js
packages/test/src/util/browser-tests-runner/driver.js
packages/test/src/util/browser-tests-runner/index.js
packages/test/src/util/browser-tests-runner/server.js
packages/test/src/util/browser-tests-runner/util/wdio-defaults.js

Add default chrome driver options for CI usage and run chrome headless by default.
Exposes a `--debug` option which replaces the `--no-exit` option.
`--debug` keeps the server alive, while also disabling the headless mode in local browser tests.

Local chrome driver improvements

---

packages/prettyprint/package-lock.json
packages/prettyprint/package.json
packages/prettyprint/src/prettyPrintSource.js
packages/prettyprint/src/printHtmlElement.js
packages/prettyprint/src/printNodes.js
packages/prettyprint/src/printText.js
packages/prettyprint/src/util/getBodyText.js
packages/prettyprint/src/util/getTextValue.js
packages/prettyprint/src/util/indent.js
packages/prettyprint/src/util/toCode.js
packages/prettyprint/src/util/unescapePlaceholdersInStringExpression.js
packages/prettyprint/test/autotest/attr-template-literal/expected.marko
packages/prettyprint/test/autotest/dynamic-tag-name/expected.marko
packages/prettyprint/test/autotest/placeholders-string-double-backslash/expected.marko
packages/prettyprint/test/util/autotest.js

Uses the new `compiler.parse` api in Marko to parse with placeholders in the ast.  Updates the printing logic to handle these new nodes.
The migration ast includes these nodes, so we need to be able to print them properly.

Prettyprint: parse with placeholders and fix printing of nodes

---

packages/migrate/README.md
packages/migrate/src/cli.js
packages/migrate/src/index.js
packages/migrate/src/util/migrate-helper.js
packages/migrate/test/index.test.js

Exposes a `prompt` option on the `migrate` programmatic api which enables mocking.
Also renames `patterns` option to `files`.

feat(migrate): provide ability to override prompts in programatic api

---

packages/migrate/README.md
packages/migrate/package-lock.json
packages/migrate/package.json
packages/migrate/src/cli.js
packages/migrate/src/index.js
packages/migrate/src/util/default-migrations/component-file.js
packages/migrate/src/util/default-migrations/index.js
packages/migrate/src/util/default-migrations/rename-file.js
packages/migrate/test/fixtures/single-template-rename/snapshot-expected.marko
packages/migrate/test/index.test.js

This change adds leverages [dependent-path-update]() to automatically update paths in dependent files while renaming during migration.
This also includes a breaking change where the programatic API now exposes an `updated` property for migrated files and a `moved` property for moved files. This was done because these need to happen at different stages in the CI as a migrated file could also need to be updated if one of it's dependencies also moved.

feat(migrate): update dependent paths when renaming files

---

packages/prettyprint/src/printHtmlElement.js
packages/prettyprint/test/autotest/dynamic-tag-name/expected.marko

Added logic to shorten the end tag of dynamic tags

Shorten end tag of dynamic tags

---

packages/migrate/src/index.js

Currently file migrations run in parallel but this breaks down with migrations that require prompts. This can cause multiple prompts to be displayed at once which is confusing.
This PR changes migrations to run on one file at a time.

fix(migrate): run migrations serially

---

packages/migrate/README.md
packages/migrate/src/cli.js
packages/migrate/src/index.js
packages/migrate/src/util/default-migrations/component-file.js
packages/migrate/src/util/default-migrations/index.js
packages/migrate/src/util/default-migrations/update-paths.js
packages/migrate/test/index.test.js

BREAKING CHANGE: The migrate programtic API has been updated to allow performing IO operations while running
Currently when running `marko migrate` against multiple files where one migration would rename a file updated in a previous migration can cause an invalid output.
This change ensures each file is migrated (including renames and dependent updates) serially and exposes events from the programatic API to handle this.

fix: Multi file migrations

---

package-lock.json
packages/prettyprint/package-lock.json
packages/prettyprint/package.json
packages/prettyprint/src/printHtmlElement.js
packages/prettyprint/src/printScriptlet.js
packages/prettyprint/src/util/formatJS.js
packages/prettyprint/src/util/getUnenclosedAsString.js
packages/prettyprint/src/util/hasUnenclosedNewlines.js
packages/prettyprint/src/util/hasUnenclosedWhitespace.js
packages/prettyprint/test/autotest/attr-regex-literal/expected.marko
packages/prettyprint/test/autotest/js-line-unformatted/expected.marko

BREAKING CHANGE: RegExp are now parsed and unwrapped - requires `marko@>=4.14.21`

feat(prettyprint): remove unneeded parens (attrs) & blocks (scriptlets)

---

packages/prettyprint/package-lock.json
packages/prettyprint/src/printHtmlElement.js
packages/prettyprint/test/autotest/attr-with-newlines/expected.marko
packages/prettyprint/test/autotest/attr-with-newlines/template.marko

Fixes indentation of attributes when the content of an attribute spans multiple lines.

fix(prettyprint): attribute with multiple lines

---

packages/prettyprint/src/printHtmlElement.js
packages/prettyprint/src/util/formatJS.js
packages/prettyprint/test/autotest/attr-new/expected.marko
packages/prettyprint/test/autotest/attr-newline-nested/expected.marko
packages/prettyprint/test/autotest/attr-newline-nested/template.marko
packages/prettyprint/test/autotest/attr-object-literal/expected.marko
packages/prettyprint/test/autotest/attrs-multiline-nested/expected.marko
packages/prettyprint/test/autotest/attrs-multiline/expected.marko
packages/prettyprint/test/autotest/max-line-length/expected.marko
packages/prettyprint/test/autotest/var-array/expected.marko
packages/prettyprint/test/autotest/var-concise/expected.marko

Currently attributes that span multiple lines break when nested. This PR cleans up attribute printing and fixes this issue.

fix(prettyprint): improve printing of nested attributes

---

packages/test/README.md
packages/test/src/util/server-tests-runner/ServerContext.js

Adds a new `renderAsync` to the server side context allowing for async tests to run. (context.render was synchronous 👎).
fixes #15

feat(test): add renderAsync method to server context

---

packages/prettyprint/src/util/formatJS.js
packages/prettyprint/test/autotest/attr-arrow-function-expression/expected.marko
packages/prettyprint/test/autotest/attr-arrow-function-expression/template.marko
packages/prettyprint/test/autotest/attr-with-newlines/expected.marko

Currently we have some simple logic to remove unneeded parenthesis (added by prettier) around expression statements. This just checked if the first and last char were parens and then removed them.
This would cause false positive such as:
```js
() => a.b()
```
This PR fixes this issue by having prettier print the value as a variable declarator instead of an expression statement which means it does not need to wrap it in parenthesis and we can remove the check.
Note: This was not an issue with `(a) => b()` because prettier would output `a => b()` which does not create the false positive.
Fixes https://github.com/marko-js/marko/issues/1268

fix(prettyprint): printing expressions with uneven parens

---

packages/prettyprint/package-lock.json
packages/prettyprint/src/printNodes.js
packages/prettyprint/src/printText.js
packages/prettyprint/src/util/Writer.js
packages/prettyprint/src/util/trim.js
packages/prettyprint/test/autotest/comments-inline/expected.marko
packages/prettyprint/test/autotest/tag-whitespace/expected.marko
packages/prettyprint/test/autotest/tag-whitespace/template.marko

This commit updates the prettyprint module. It ensures that the valid and required whitespace in original marko template are preserved while pretty printing.
It was observed that when AST has Text node containing either only whitespaces or leading/trailing whitespace, it was being removed during pretty print. This caused the output template to render differently than the original template. This PR address this problem and ensures required whitespaces are preserved.

fix(prettyprint): update whitespace preservation

---

packages/migrate/package.json
packages/migrate/src/index.js
packages/prettyprint/package-lock.json
packages/prettyprint/package.json
packages/prettyprint/src/cli.js

- only write files that have changed
- `migrate` now runs `prettyprint` on the original source to use as a comparison
- don't bail on first error

fix(prettyprint,migrate): cli aggregates errors and visually shows changed paths

---

packages/build/package.json
packages/build/src/index.js
packages/build/src/util.js
packages/serve/test/fixtures/add-route/after-serve-expected.html
packages/serve/test/fixtures/add-route/build-expected.html
packages/serve/test/fixtures/add-route/serve-expected.html
packages/serve/test/fixtures/add-route/target/a.marko
packages/serve/test/fixtures/add-route/test.js

Fixes a regression where new pages added when using `@marko/serve` do not cause a recompilation.

fix: issue with adding a new route in serve

---

packages/build/src/index.js
packages/serve/test/fixtures/update/build-expected.html

Shortens generated filenames for `prod` builds with `@marko/build`.
Now entry chunks (which require a `[name]` or `[id]` prefix) use `[id]` in prod which is shorted. The external css which doesn't have this restriction follows the approach of the `file-loader` and just uses a content hash.

feat(build): shorten generated filenames for prod build

---

packages/build/src/files/server.js

Currently the `maxAge` option set was assumed to have been in seconds, like the `cache-control` header. However the `send` utility under the hood was expecting `ms`, and so we are actually not caching assets for long enough.
This PR fixes that by properly using `ms`.

fix(build): asset cache header now set to 1 year

---

packages/build/src/index.js

Removes `bail: true` from the webpack config in `@marko/build`. This option was causing `@marko/serve` to not display any errors to the user.

fix(build): remove bail option which was causing errors to be hidden

---

.travis.yml
package-lock.json
packages/build/package-lock.json
packages/build/package.json
packages/build/src/index.js
packages/create/package-lock.json

Currently client side assets which are emitted from the server side compiler in `@marko/build` do not go through the compression plugin. This means they do not have `.gz` or `.br` files created.
This PR fixes this by added the plugin to both the server and the browser compilers, the server compiler whitelists to assets added to the `/assets` folder.

Fix ssr asset compression

---

packages/build/src/index.js

The source map module was meant to be enabled in dev mode (prod should use `--enable-source-maps` flag with `node@12`. This PR fixes that module to be correctly loaded in dev mode.

fix(build): server bundle source maps in dev mode

---

package-lock.json
packages/build/README.md
packages/build/package-lock.json
packages/build/src/cli.js
packages/build/src/files/server.js
packages/build/src/index.js
packages/serve/package-lock.json
packages/serve/src/cli.js
packages/serve/src/index.js
packages/serve/test/fixtures/custom-browserslist/.browserslistrc
packages/serve/test/fixtures/custom-browserslist/build-expected.html
packages/serve/test/fixtures/custom-browserslist/serve-expected.html
packages/serve/test/fixtures/custom-browserslist/target.marko
packages/serve/test/fixtures/custom-webpack-config/build-expected.html
packages/serve/test/fixtures/custom-webpack-config/serve-expected.html
packages/serve/test/fixtures/custom-webpack-config/target.marko
packages/serve/test/fixtures/custom-webpack-config/webpack.config.js
packages/serve/test/index.test.js

This changes the programatic api for `@marko/build` and as such is a BREAKING CHANGE
Allows using a custom `webpack.config.js` and provides helper functions to use the default base configs. Example:
```js
import path from "path";
import { configBuilder } from "@marko/build";
import MyPlugin from "my-plugin";
const { getServerConfig, getBrowserConfigs } = configBuilder({
entry: path.join(__dirname, "target.marko"),
production: process.env.NODE_ENV === "production"
});
module.exports = [
...getBrowserConfigs(config => {
config.plugins.push(new MyPlugin());
return config;
}),
getServerConfig(config => {
config.plugins.push(new MyPlugin());
return config;
})
];
```

feat: add support for custom webpack.config.js

---

packages/build/src/index.js

Excludes `components/` from files discovered to create pages.
Including `components/` directories ends up creating many more entry points than likely intended, increasing the amount of work done by the builder.

feat: exclude components directory from served pages

---

packages/create-alias/package.json
packages/create-alias/src/index.js
packages/create/README.md
packages/create/src/cli.js
packages/create/src/index.js

Adds support for a new `--installer` option for `@marko/create` which allows you to override the package manager used to install the dependencies. Also the default package manager is now automatically determined in cases where a package manager is used to run `@marko/create`, eg `yarn create marko` will use `yarn`.
Resolves #185
This PR also releases an alias package `marko-create` to support `yarn create`.

feat(create): add support for package managers besides npm

---

packages/create/src/init-git-repo.js

Adds a fallback git author if missing to account for when users to not have `user.name` and `user.email` configured for git.
Resolves #184

fix(create): use a fallback git author if missing

---

packages/create/README.md

add command forwarding separator, remove `@` prefix
closes #213 
```console
❯ npm init marko -- anappyay --template tags-api
✔ Project created! To get started, run:
cd anappyay
npm run dev
❯ npm init marko anappyay2 -- --template tags-api
✔ Project created! To get started, run:
cd anappyay2
npm run dev
❯ npm init marko ./anappyay3 -- --template tags-api
✖ Invaid app name: ./anappyay3
Error: Invaid app name: ./anappyay3
```
```console
❯ npm search create-marko
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
create-marko              | Create Marko…        | =ryansolid…     | 2021-05-04 | 6.1.1    | create demo marko util utility
~/src/wip/marko
❯ npm search @marko/create
NAME                      | DESCRIPTION          | AUTHOR …
```

fix(docs): npm init command
